Klassifikation på churn.csv

In [3]:
import numpy as np
import pandas as pd

In [4]:
churn = pd.read_csv("churn.csv")

Kollar så inga värden är NaN

In [5]:
churn.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Kollar vilka kategorier jag kan göra om med LabelEncoder

In [6]:
print(churn["gender"].nunique())
print(churn["SeniorCitizen"].nunique())
print(churn["Partner"].nunique())
print(churn["Dependents"].nunique())
print(churn["PhoneService"].nunique())
print(churn["PaperlessBilling"].nunique())

2
2
2
2
2
2


Hittar värden som börjar med space. Kunde inte göra om dessa till float värden så fick hitta medelvärden för kolumnen "TotalCharges" och sen sätta in det där det saknades värden

In [7]:
has_space = churn["TotalCharges"].str.startswith(' ')

Kollar raderna som saknar värden

In [8]:
print(churn[has_space])

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0   
753   3115-CZMZD    Male              0      No        Yes       0   
936   5709-LVOEQ  Female              0     Yes        Yes       0   
1082  4367-NUYAO    Male              0     Yes        Yes       0   
1340  1371-DWPAZ  Female              0     Yes        Yes       0   
3331  7644-OMVMY    Male              0     Yes        Yes       0   
3826  3213-VVOLG    Male              0     Yes        Yes       0   
4380  2520-SGTTA  Female              0     Yes        Yes       0   
5218  2923-ARZLG    Male              0     Yes        Yes       0   
6670  4075-WKNIU  Female              0     Yes        Yes       0   
6754  2775-SEFEE    Male              0      No        Yes       0   

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ... 

Medelvärdet på "TotalCharges" minus där värdena saknades

In [9]:
mean_value = pd.to_numeric(churn["TotalCharges"][~has_space]).mean()

In [10]:
mean_value

2283.300440841866

Tar bort ' ' i början av raden och sätter in medelvärdet

In [11]:
churn["TotalCharges"] = churn["TotalCharges"].str.strip()
churn.loc[has_space, "TotalCharges"] = mean_value

In [12]:
print(churn[has_space])

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0   
753   3115-CZMZD    Male              0      No        Yes       0   
936   5709-LVOEQ  Female              0     Yes        Yes       0   
1082  4367-NUYAO    Male              0     Yes        Yes       0   
1340  1371-DWPAZ  Female              0     Yes        Yes       0   
3331  7644-OMVMY    Male              0     Yes        Yes       0   
3826  3213-VVOLG    Male              0     Yes        Yes       0   
4380  2520-SGTTA  Female              0     Yes        Yes       0   
5218  2923-ARZLG    Male              0     Yes        Yes       0   
6670  4075-WKNIU  Female              0     Yes        Yes       0   
6754  2775-SEFEE    Male              0      No        Yes       0   

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ... 

In [13]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

Kör LabelEncoder på värdena som bara hade 2 värden

In [14]:
columnsToEncode = ["gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "PaperlessBilling"]

In [15]:
for column in columnsToEncode:
  churn[column] = labelEncoder.fit_transform(churn[column])

In [16]:
churn

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     7590-VHVEG       0              0        1           0       1   
1     5575-GNVDE       1              0        0           0      34   
2     3668-QPYBK       1              0        0           0       2   
3     7795-CFOCW       1              0        0           0      45   
4     9237-HQITU       0              0        0           0       2   
...          ...     ...            ...      ...         ...     ...   
7038  6840-RESVB       1              0        1           1      24   
7039  2234-XADUH       0              0        1           1      72   
7040  4801-JZAZL       0              0        1           1      11   
7041  8361-LTMKD       1              1        1           0       4   
7042  3186-AJIEK       1              0        0           0      66   

      PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0                0  No phone service             DSL             No  ...   
1                1                No             DSL            Yes  ...   
2                1                No             DSL            Yes  ...   
3                0  No phone service             DSL            Yes  ...   
4                1                No     Fiber optic             No  ...   
...            ...               ...             ...            ...  ...   
7038             1               Yes             DSL            Yes  ...   
7039             1               Yes     Fiber optic             No  ...   
7040             0  No phone service             DSL            Yes  ...   
7041             1               Yes     Fiber optic             No  ...   
7042             1                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                   1           Electronic check          29.85         29.85   
1                   0               Mailed check          56.95        1889.5   
2                   1               Mailed check          53.85        108.15   
3                   0  Bank transfer (automatic)          42.30       1840.75   
4                   1           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038                1               Mailed check          84.80        1990.5   
7039                1    Credit card (automatic)         103.20        7362.9   
7040                1           Electronic check          29.60        346.45   
7041                1               Mailed check          74.40         306.6   
7042                1  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

Sätter X till alla kolumner förutom Churn och customerID då jag ansåg att customerID inte har någon mening när vi ska förutsäga y = Churn

In [17]:
X = churn.drop(columns=["Churn", "customerID"])
y = churn["Churn"]

In [18]:
X

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0   
1          1              0        0           0      34             1   
2          1              0        0           0       2             1   
3          1              0        0           0      45             0   
4          0              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7038       1              0        1           1      24             1   
7039       0              0        1           1      72             1   
7040       0              0        1           1      11             0   
7041       1              1        1           0       4             1   
7042       1              0        0           0      66             1   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

      PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  
0                    1           Electronic check           29.85        29.85  
1                    0               Mailed check           56.95       1889.5  
2                    1               Mailed check           53.85       108.15  
3                    0  Bank transfer (automatic)           42.30      1840.75  
4                    1           Electronic check           70.70       151.65  
...                ...                        ...             ...          ...  
7038                 1               Mailed check           84.80       1990.5  
7039                 1    Credit card (automatic)          103.20       7362.9  
7040                 1           Electronic check           29.60       346.45  
7041                 1               Mailed check           74.40        306.6  
7042                 1  Bank transfer (automatic)          105.65       6844.5  

[7043 rows x 19 columns]

In [19]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ... 
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

Kör OneHotEncoder på de andra kolumnerna som har fler än 2 värden i sig och är i strängformat

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [21]:
columnTransformer = ColumnTransformer(transformers=[("encoder", OneHotEncoder(),
 ["MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV",
  "StreamingMovies", "Contract", "PaymentMethod"])], remainder="passthrough")

In [22]:
X = columnTransformer.fit_transform(X)

In [23]:
print(X)

[[0.0 1.0 0.0 ... 1 29.85 '29.85']
 [1.0 0.0 0.0 ... 0 56.95 '1889.5']
 [1.0 0.0 0.0 ... 1 53.85 '108.15']
 ...
 [0.0 1.0 0.0 ... 1 29.6 '346.45']
 [0.0 0.0 1.0 ... 1 74.4 '306.6']
 [1.0 0.0 0.0 ... 1 105.65 '6844.5']]


In [24]:
churn["Churn"].unique()

array(['No', 'Yes'], dtype=object)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

Tränar datan med RobustScaler för att slippa "outliers"

In [27]:
from sklearn.preprocessing import RobustScaler
robust = RobustScaler()

In [28]:
X_train = robust.fit_transform(X_train)
X_test = robust.transform(X_test)

In [29]:
y_train

5860    Yes
2458     No
5879     No
4708     No
1293     No
       ... 
3046     No
1725     No
4079     No
2254     No
2915     No
Name: Churn, Length: 5634, dtype: object

Logistic Regression

Testar Logistic Regression som presterar rätt bra om vi jämför med de andra modellerna jag testar här under

In [30]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [31]:
model.fit(X_train, y_train)

LogisticRegression()

In [32]:
result = model.predict(X_test)

In [33]:
result

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [35]:
confusion_matrix(y_test, result)

array([[914, 109],
       [183, 203]])

In [36]:
accuracy_score(y_test, result)

0.7927608232789212

In [37]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

          No       0.83      0.89      0.86      1023
         Yes       0.65      0.53      0.58       386

    accuracy                           0.79      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.78      0.79      0.79      1409



Decision Tree

Decision Tree presterade sämst av alla modellerna, kanske förutsägbart då den brukar vara sisådär

In [38]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [39]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [40]:
result = model.predict(X_test)

In [41]:
result

array(['No', 'No', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [42]:
confusion_matrix(y_test, result)

array([[801, 222],
       [193, 193]])

In [43]:
accuracy_score(y_test, result)

0.7054648687012065

In [44]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

          No       0.81      0.78      0.79      1023
         Yes       0.47      0.50      0.48       386

    accuracy                           0.71      1409
   macro avg       0.64      0.64      0.64      1409
weighted avg       0.71      0.71      0.71      1409



Random Forest

Bättre resultat här men slår inte Logistic Regression

In [45]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)

In [46]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [47]:
result = model.predict(X_test)

In [48]:
result

array(['Yes', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [49]:
confusion_matrix(y_test, result)

array([[924,  99],
       [192, 194]])

In [50]:
accuracy_score(y_test, result)

0.7934705464868701

In [51]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1023
         Yes       0.66      0.50      0.57       386

    accuracy                           0.79      1409
   macro avg       0.75      0.70      0.72      1409
weighted avg       0.78      0.79      0.78      1409



Closest Neighbors

Helt okej resultat på Closest Neighbors. Testade även att ändra n_neighbors till olika värden. Till exempel med n_neighbors=100 får vi ett accuracy score på 7.86. Såg även att modellen blev sämre när man prioriterade de närmsta värdena (weights="distance") vid låga neighbors men bättre om man höjde det värdet.

In [52]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=100)

In [53]:
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=100)

In [54]:
result = model.predict(X_test)

In [55]:
result

array(['No', 'Yes', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [56]:
confusion_matrix(y_test, result)

array([[891, 132],
       [169, 217]])

In [57]:
accuracy_score(y_test, result)

0.7863733144073811

In [58]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

          No       0.84      0.87      0.86      1023
         Yes       0.62      0.56      0.59       386

    accuracy                           0.79      1409
   macro avg       0.73      0.72      0.72      1409
weighted avg       0.78      0.79      0.78      1409



SVM LINEAR

Presterar helt okej jämfört med de andra modellerna

In [59]:
from sklearn.svm import SVC
model = SVC(kernel="linear")

In [60]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [61]:
result = model.predict(X_test)

In [62]:
result

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [63]:
confusion_matrix(y_test, result)

array([[913, 110],
       [194, 192]])

In [64]:
accuracy_score(y_test, result)

0.7842441447835344

In [65]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

          No       0.82      0.89      0.86      1023
         Yes       0.64      0.50      0.56       386

    accuracy                           0.78      1409
   macro avg       0.73      0.69      0.71      1409
weighted avg       0.77      0.78      0.78      1409



SVM RBF

Bästa modellen av alla testerna! Score på nästan 0.8.

In [66]:
from sklearn.svm import SVC
model = SVC(kernel="rbf")

In [67]:
model.fit(X_train, y_train)

SVC()

In [68]:
result = model.predict(X_test)

In [69]:
result

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [70]:
confusion_matrix(y_test, result)

array([[928,  95],
       [195, 191]])

In [71]:
accuracy_score(y_test, result)

0.794180269694819

In [72]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

          No       0.83      0.91      0.86      1023
         Yes       0.67      0.49      0.57       386

    accuracy                           0.79      1409
   macro avg       0.75      0.70      0.72      1409
weighted avg       0.78      0.79      0.78      1409



Skulle ändra vilja säga att den gör bra ifrån sig och att 0.8 är ett relativt bra resultat om man tänker på hur många kolumner och den ska ha i åtanke och hur många olika varianter det finns när svaren är Ja/Nej eller 0 och 1. Enklare att förutspå ett korrekt värde när värdena kanske skiljer sig från till exmepel 0.5-0.7 och allt därimellan

Märkte att det blev rätt mycket kod här så skickar in i två olika .ipynb filer!